#pragma once

#define SYSTEM_NODE_ID   1
#define CONTROL_NODE_ID  2
#define EXT_COMM_NODE_ID 3

// Packet Signatures
#define SYSTEM_NODE_SIGNATURE   0x1515
#define CONTROL_NODE_SIGNATURE  0x2525
#define EXT_COMM_NODE_SIGNATURE 0x3535